# Generated by Django 5.1.7 on 2025-04-04 13:18

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('piece', 'Dona'), ('kg', 'Kilogramm'), ('g', 'Gram'), ('m', 'Metr'), ('bag', 'Xalta'), ('pack', 'Pachka')], default='piece', max_length=255, null=True, verbose_name='Kategoriya')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('none', 'Aniq emas')], default='active', max_length=10, verbose_name='Holati')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Mahsulot rasmi')),
                ('user', models.ForeignKey(default=common.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
