# Generated by Django 5.1.7 on 2025-04-05 13:50

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Admin ismi')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Admin telefon raqami')),
                ('age', models.IntegerField(verbose_name='Admin yoshi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Admin email adresi (shart emas)')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Admin manzili (shart emas)')),
                ('status', models.CharField(choices=[('active', 'Aktiv admin'), ('inactive', 'Aktiv emas'), ('deleted', "O'chirilgan")], default='active', max_length=10, verbose_name='Admin holati')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Admin oylik narxi')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Admin username')),
                ('password', models.CharField(max_length=255, verbose_name='Admin paroli')),
                ('password_confirmation', models.CharField(max_length=255, verbose_name='Parolini tasdiqlang.')),
                ('user', models.ForeignKey(default=common.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
        migrations.CreateModel(
            name='MentorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name="O'qituvchi ismi")),
                ('phone_number', models.CharField(max_length=15, verbose_name="O'qituvchi telefon raqami")),
                ('age', models.IntegerField(verbose_name="O'qituvchi yoshi")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="O'qituvchi email manzili (shart emas)")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name="O'qituvchi manzili (shart emas)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="O'qituvchi oylik narxi")),
                ('status', models.CharField(choices=[('active', 'Ishlayapti'), ('inactive', 'Ishlamayapti'), ('deleted', "O'chirilgan")], default='active', max_length=10, verbose_name='Holati')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qanday O'qituvchi")),
                ('username', models.CharField(max_length=255, unique=True, verbose_name="O'qituvchi username")),
                ('password', models.CharField(max_length=255, verbose_name="O'qituvchi paroli")),
                ('password_confirmation', models.CharField(max_length=255, verbose_name='Parolini tasdiqlang.')),
                ('user', models.ForeignKey(default=common.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('start_date', models.CharField(max_length=150, verbose_name='Dars vaqtlari')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Guruh haqida ma'lumot")),
                ('status', models.CharField(choices=[('active', 'Aktiv guruh'), ('inactive', 'Aktiv emas'), ('deleted', "O'chirilgan")], default='active', max_length=10, verbose_name='Guruh Holati')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kurs narxi')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mentormodel', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name="O'quvchi to'lliq ismi")),
                ('age', models.IntegerField(verbose_name="O'quvchi yoshi")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name="O'quvchi manzili (shart emas)")),
                ('phone_number', models.CharField(max_length=15, verbose_name="O'quvchi telefon raqami")),
                ('parents_phone_number', models.CharField(max_length=15, verbose_name='Ota-onasi telefon raqami')),
                ('status', models.CharField(choices=[('active', "Aktiv o'quvchi"), ('inactive', 'Aktiv emas'), ('deleted', "O'chirilgan")], default='active', max_length=10, verbose_name="O'quvchi holati")),
                ('username', models.CharField(max_length=255, unique=True, verbose_name="O'quvchi username")),
                ('password', models.CharField(max_length=255, verbose_name="O'quvchi paroli")),
                ('password_confirmation', models.CharField(max_length=255, verbose_name='Parolini tasdiqlang.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.groupmodel', verbose_name='Guruh')),
                ('user', models.ForeignKey(default=common.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Kelgan'), ('inactive', 'Kelmagan'), ('because', 'Sababli')], default='active', max_length=10, verbose_name='Davomat holati')),
                ('coin', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tangalar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.studentmodel', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
            },
        ),
    ]
