# Generated by Django 5.1.7 on 2025-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_attendancemodel_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='coin',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Tangalar'),
        ),
    ]
