# Generated by Django 5.1.7 on 2025-04-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO (Boshqaruvchi)'), ('mentor', 'Mentor'), ('admin', 'Administrator'), ('student', "O'quvchi")], default='student', max_length=15),
        ),
    ]
